In [103]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [104]:
df = pd.read_csv('World Energy Consumption.csv')
df

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,...,solar_elec_per_capita,solar_energy_per_capita,gdp,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
0,AFG,Afghanistan,1900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1901,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,1902,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Afghanistan,1903,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Afghanistan,1904,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17427,ZWE,Zimbabwe,2015,-25.013,-10.847,NaN,NaN,NaN,NaN,-0.789,...,0.579,NaN,2.503057e+10,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17428,ZWE,Zimbabwe,2016,-37.694,-12.257,NaN,NaN,NaN,NaN,-14.633,...,0.641,NaN,2.515176e+10,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17429,ZWE,Zimbabwe,2017,8.375,1.697,NaN,NaN,NaN,NaN,NaN,...,0.773,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17430,ZWE,Zimbabwe,2018,22.555,4.952,NaN,NaN,NaN,NaN,NaN,...,0.970,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17431,ZWE,Zimbabwe,2019,-35.015,-9.422,NaN,NaN,NaN,NaN,NaN,...,0.956,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN

In [105]:
col = ['iso_code', 'country', 'year', 'gdp', 'population', 'fossil_fuel_consumption', 'coal_consumption', 'coal_production', \
       'gas_consumption', 'gas_production', 'oil_consumption', 'oil_production', 'low_carbon_consumption', 'renewables_consumption', \
       'biofuel_consumption', 'hydro_consumption', 'solar_consumption', 'wind_consumption', 'other_renewable_consumption', \
       'nuclear_consumption']

df = df[col]
df

,iso_code,country,year,gdp,population,fossil_fuel_consumption,coal_consumption,coal_production,gas_consumption,gas_production,oil_consumption,oil_production,low_carbon_consumption,renewables_consumption,biofuel_consumption,hydro_consumption,solar_consumption,wind_consumption,other_renewable_consumption,nuclear_consumption
0,AFG,Afghanistan,1900,NaN,5021241.0,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1901,NaN,5053439.0,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,1902,NaN,5085403.0,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Afghanistan,1903,NaN,5118005.0,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Afghanistan,1904,NaN,5150814.0,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17427,ZWE,Zimbabwe,2015,2.503057e+10,13815000.0,NaN,NaN,32.517,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
17428,ZWE,Zimbabwe,2016,2.515176e+10,14030000.0,NaN,NaN,20.260,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
17429,ZWE,Zimbabwe,2017,NaN,14237000.0,NaN,NaN,21.957,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
17430,ZWE,Zimbabwe,2018,NaN,14439000.0,NaN,NaN,26.910,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
17431,ZWE,Zimbabwe,2019,NaN,14645000.0,NaN,NaN,17.487,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN

In [106]:
df = df.dropna(subset=['iso_code'], how='any')
df

,iso_code,country,year,gdp,population,fossil_fuel_consumption,coal_consumption,coal_production,gas_consumption,gas_production,oil_consumption,oil_production,low_carbon_consumption,renewables_consumption,biofuel_consumption,hydro_consumption,solar_consumption,wind_consumption,other_renewable_consumption,nuclear_consumption
0,AFG,Afghanistan,1900,NaN,5021241.0,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1901,NaN,5053439.0,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,1902,NaN,5085403.0,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Afghanistan,1903,NaN,5118005.0,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Afghanistan,1904,NaN,5150814.0,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17427,ZWE,Zimbabwe,2015,2.503057e+10,13815000.0,NaN,NaN,32.517,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
17428,ZWE,Zimbabwe,2016,2.515176e+10,14030000.0,NaN,NaN,20.260,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
17429,ZWE,Zimbabwe,2017,NaN,14237000.0,NaN,NaN,21.957,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
17430,ZWE,Zimbabwe,2018,NaN,14439000.0,NaN,NaN,26.910,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
17431,ZWE,Zimbabwe,2019,NaN,14645000.0,NaN,NaN,17.487,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN

In [107]:
df = df[(df['year'] >= 2000) & (df['year'] <= 2016)].reset_index().iloc[:,1:]
df = df.fillna(0)
df.head(50)

,iso_code,country,year,gdp,population,fossil_fuel_consumption,coal_consumption,coal_production,gas_consumption,gas_production,oil_consumption,oil_production,low_carbon_consumption,renewables_consumption,biofuel_consumption,hydro_consumption,solar_consumption,wind_consumption,other_renewable_consumption,nuclear_consumption
0,AFG,Afghanistan,2000,1.650883e+10,20780000.0,0.000,0.000,0.006,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
1,AFG,Afghanistan,2001,1.557484e+10,21607000.0,0.000,0.000,0.151,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
2,AFG,Afghanistan,2002,2.567680e+10,22601000.0,0.000,0.000,0.122,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
3,AFG,Afghanistan,2003,2.780556e+10,23681000.0,0.000,0.000,0.203,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
4,AFG,Afghanistan,2004,2.844769e+10,24727000.0,0.000,0.000,0.197,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
5,AFG,Afghanistan,2005,3.125965e+10,25654000.0,0.000,0.000,0.192,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
6,AFG,Afghanistan,2006,3.413258e+10,26433000.0,0.000,0.000,0.203,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
7,AFG,Afghanistan,2007,3.962899e+10,27101000.0,0.000,0.000,1.411,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
8,AFG,Afghanistan,2008,4.056158e+10,27722000.0,0.000,0.000,2.015,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
9,AFG,Afghanistan,2009,4.753980e+10,28395000.0,0.000,0.000,2.903,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
10,AFG,Afghanistan,2010,4.906888e+10,29186000.0,0.000,0.000,4.209,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
11,AFG,Afghanistan,2011,5.332634e+10,30117000.0,0.000,0.000,8.592,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
12,AFG,Afghanistan,2012,5.916690e+10,31161000.0,0.000,0.000,7.199,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
13,AFG,Afghanistan,2013,6.299370e+10,32270000.0,0.000,0.000,7.820,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
14,AFG,Afghanistan,2014,6.434611e+10,33371000.0,0.000,0.000,8.810,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
15,AFG,Afghanistan,2015,6.278339e+10,34414000.0,0.000,0.000,7.925,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
16,AFG,Afghanistan,2016,6.429743e+10,35383000.0,0.000,0.000,9.858,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
17,ALB,Albania,2000,1.639901e+10,3129000.0,0.000,0.000,0.082,0.000,0.324,0.000,3.829,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
18,ALB,Albania,2001,1.695181e+10,3130000.0,0.000,0.000,0.057,0.000,0.324,0.000,4.018,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
19,ALB,Albania,2002,1.703786e+10,3126000.0,0.000,0.000,0.041,0.000,0.324,0.000,4.294,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
20,ALB,Albania,2003,1.784730e+10,3118000.0,0.000,0.000,0.159,0.000,0.324,0.000,4.534,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
21,ALB,Albania,2004,1.859279e+10,3105000.0,0.000,0.000,0.159,0.000,0.324,0.000,4.530,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
22,ALB,Albania,2005,1.969197e+10,3087000.0,0.000,0.000,0.123,0.000,0.324,0.000,4.725,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
23,ALB,Albania,2006,2.141122e+10,3063000.0,0.000,0.000,0.123,0.000,0.324,0.000,5.227,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
24,ALB,Albania,2007,2.299598e+10,3034000.0,0.000,0.000,0.123,0.000,0.107,0.000,4.333,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
25,ALB,Albania,2008,2.576483e+10,3003000.0,0.000,0.000,0.167,0.000,0.314,0.000,4.061,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
26,ALB,Albania,2009,2.800652e+10,2973000.0,0.000,0.000,0.027,0.000,0.314,0.000,3.597,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
27,ALB,Albania,2010,2.789741e+10,2948000.0,0.000,0.000,0.027,0.000,0.103,0.000,7.320,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
28,ALB,Albania,2011,2.845200e+10,2929000.0,0.000,0.000,0.014,0.000,0.103,0.000,10.473,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
29,ALB,Albania,2012,3.111475e+10,2914000.0,0.000,0.000,0.014,0.000,0.176,0.000,11.396,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
30,ALB,Albania,2013,3.058635e+10,2904000.0,0.000,0.000,0.008,0.000,0.197,0.000,11.481,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
31,ALB,Albania,2014,3.238728e+10,2896000.0,0.000,0.000,0.000,0.000,0.331,0.000,13.843,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
32,ALB,Albania,2015,3.322414e+10,2891000.0,0.000,0.000,0.000,0.000,0.362,0.000,13.610,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
33,ALB,Albania,2016,3.435154e+10,2886000.0,0.000,0.000,0.000,0.000,0.466,0.000,15.398,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.0
34,DZA,Algeria,2000,2.520000e+11,31042000.0,299.786,5.641,0.000,191.013,918.887,103.133,775.472,0.150,0.150,0.0,0.150,0.000,0.000,0.0,0.0
35,DZA,Algeria,2001,2.520000e+11,31452000.0,310.611,6.513,0.000,197.322,864.726,106.775,763.443,0.190,0.190,0.0,0.190,0.000,0.000,0.0,0.0
36,DZA,Algeria,2002,2.660000e+11,31855000.0,321.784,8.548,0.000,194.839,889.417,118.397,823.159,0.156,0.156,0.0,0.156,0.000,0.000,0.0,0.0
37,DZA,Algeria,2003,2.890000e+11,32264000.0,336.154,7.048,0.000,205.932,938.577,123.174,917.337,0.722,0.722,0.0,0.722,0.000,0.000,0.0,0.0
38,DZA,Algeria,2004,3.080000e+11,32692000.0,349.055,8.408,0.000,211.899,920.550,128.747,970.121,0.679,0.679,0.0,0.679,0.000,0.000,0.0,0.0
39,DZA,Algeria,2005,3.540000e+11,33150000.0,364.682,6.908,0.000,223.560,849.118,134.213,1003.638,1.494,1.494,0.0,1.494,0.000,0.000,0.0,0.0
40,DZA,Algeria,2006,3.860000e+11,33641000.0,378.601,10.258,0.000,228.498,812.996,139.846,1000.902,0.582,0.582,0.0,0.582,0.000,0.000,0.0,0.0
41,DZA,Algeria,2007,3.980000e+11,34167000.0,399.001,8.804,0.000,233.807,816.461,156.390,1004.153,0.600,0.600,0.0,0.600,0.000,0.000,0.0,0.0
42,DZA,Algeria,2008,4.230000e+11,34731000.0,422.762,8.804,0.000,244.042,826.009,169.916,984.170,0.747,0.747,0.0,0.747,0.000,0.000,0.0,0.0
43,DZA,Algeria,2009,3.920000e+11,35334000.0,447.905,5.652,0.000,262.118,765.669,180.135,896.773,0.897,0.897,0.0,0.897,0.000,0.000,0.0,0.0
44,DZA,Algeria,2010,4.480000e+11,35977000.0,436.927,3.605,0.000,253.272,773.966,180.049,856.610,0.475,0.475,0.0,0.451,0.024,0.000,0.0,0.0
45,DZA,Algeria,2011,4.820000e+11,36661000.0,463.396,3.198,0.000,267.970,795.988,192.228,832.227,1.027,1.027,0.0,0.980,0.047,0.000,0.0,0.0
46,DZA,Algeria,2012,4.930000e+11,37384000.0,506.532,3.396,0.000,298.741,784.438,204.395,780.407,1.071,1.071,0.0,1.002,0.069,0.000,0.0,0.0
47,DZA,Algeria,2013,4.930000e+11,38140000.0,536.629,1.838,0.000,321.215,793.389,213.577,752.215,0.327,0.327,0.0,0.253,0.073,0.000,0.0,0.0
48,DZA,Algeria,2014,4.940000e+11,38924000.0,584.926,2.082,0.000,360.919,801.725,221.925,798.508,0.646,0.646,0.0,0.491,0.153,0.003,0.0,0.0
49,DZA,Algeria,2015,5.130000e+11,39728000.0,616.921,1.547,0.000,379.225,814.112,236.149,780.558,0.562,0.562,0.0,0.367,0.147,0.048,0.0,0.0

In [108]:
df = df[df['gdp'] != 0]
df

,iso_code,country,year,gdp,population,fossil_fuel_consumption,coal_consumption,coal_production,gas_consumption,gas_production,oil_consumption,oil_production,low_carbon_consumption,renewables_consumption,biofuel_consumption,hydro_consumption,solar_consumption,wind_consumption,other_renewable_consumption,nuclear_consumption
0,AFG,Afghanistan,2000,1.650883e+10,20780000.0,0.0,0.0,0.006,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,AFG,Afghanistan,2001,1.557484e+10,21607000.0,0.0,0.0,0.151,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,AFG,Afghanistan,2002,2.567680e+10,22601000.0,0.0,0.0,0.122,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,AFG,Afghanistan,2003,2.780556e+10,23681000.0,0.0,0.0,0.203,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,AFG,Afghanistan,2004,2.844769e+10,24727000.0,0.0,0.0,0.197,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3664,ZWE,Zimbabwe,2012,2.048226e+10,13115000.0,0.0,0.0,11.950,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3665,ZWE,Zimbabwe,2013,2.374258e+10,13350000.0,0.0,0.0,23.353,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3666,ZWE,Zimbabwe,2014,2.474828e+10,13587000.0,0.0,0.0,43.364,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3667,ZWE,Zimbabwe,2015,2.503057e+10,13815000.0,0.0,0.0,32.517,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3668,ZWE,Zimbabwe,2016,2.515176e+10,14030000.0,0.0,0.0,20.260,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [109]:
df = df[(df.fossil_fuel_consumption != 0) | (df.low_carbon_consumption != 0)].reset_index().iloc[:,1:]
df.to_csv('energy_consumption.csv', index=False)
df

,iso_code,country,year,gdp,population,fossil_fuel_consumption,coal_consumption,coal_production,gas_consumption,gas_production,oil_consumption,oil_production,low_carbon_consumption,renewables_consumption,biofuel_consumption,hydro_consumption,solar_consumption,wind_consumption,other_renewable_consumption,nuclear_consumption
0,DZA,Algeria,2000,2.520000e+11,3.104200e+07,299.786,5.641,0.000,191.013,918.887,103.133,775.472,0.150,0.150,0.000,0.150,0.000,0.000,0.000,0.000
1,DZA,Algeria,2001,2.520000e+11,3.145200e+07,310.611,6.513,0.000,197.322,864.726,106.775,763.443,0.190,0.190,0.000,0.190,0.000,0.000,0.000,0.000
2,DZA,Algeria,2002,2.660000e+11,3.185500e+07,321.784,8.548,0.000,194.839,889.417,118.397,823.159,0.156,0.156,0.000,0.156,0.000,0.000,0.000,0.000
3,DZA,Algeria,2003,2.890000e+11,3.226400e+07,336.154,7.048,0.000,205.932,938.577,123.174,917.337,0.722,0.722,0.000,0.722,0.000,0.000,0.000,0.000
4,DZA,Algeria,2004,3.080000e+11,3.269200e+07,349.055,8.408,0.000,211.899,920.550,128.747,970.121,0.679,0.679,0.000,0.679,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1355,OWID_WRL,World,2012,9.660000e+13,7.125828e+09,126562.097,44185.345,45472.178,33220.032,33189.098,49156.720,47910.560,19266.268,12902.067,764.713,9400.811,259.658,1367.349,1109.535,6364.201
1356,OWID_WRL,World,2013,9.930000e+13,7.210582e+09,128448.117,44993.467,46289.106,33766.139,33578.499,49688.511,48010.780,20137.543,13753.829,817.131,9764.870,356.169,1627.737,1187.923,6383.714
1357,OWID_WRL,World,2014,1.020000e+14,7.295291e+09,128962.368,44954.435,46126.101,33994.279,34259.127,50013.654,49124.149,20829.361,14362.387,875.835,9910.341,503.532,1797.902,1274.776,6466.974
1358,OWID_WRL,World,2015,1.050000e+14,7.379797e+09,129516.270,43844.173,44910.763,34780.121,35006.430,50891.976,50658.259,21365.767,14849.694,907.399,9827.171,649.740,2103.669,1361.715,6516.074
1359,OWID_WRL,World,2016,1.070000e+14,7.464022e+09,130705.831,43195.639,42583.893,35590.036,35403.607,51920.156,50843.437,22239.107,15663.156,944.501,10091.741,825.450,2423.694,1377.770,6575.951

In [110]:
'''
Should delete this before submission
'''

# df[(df['year'] == 2016) & ((df['population'] >= 70000000) & (df['population'] <= 110000000))]
df[df['country'].isin(['Vietnam', 'Philippines', 'Egypt', 'Iran', 'Turkey', 'Germany'])]

,iso_code,country,year,gdp,population,fossil_fuel_consumption,coal_consumption,coal_production,gas_consumption,gas_production,oil_consumption,oil_production,low_carbon_consumption,renewables_consumption,biofuel_consumption,hydro_consumption,solar_consumption,wind_consumption,other_renewable_consumption,nuclear_consumption
323,EGY,Egypt,2000,3.550000e+11,68832000.0,525.830,10.111,0.000,192.500,202.125,323.219,451.871,39.608,39.608,0.0,39.383,0.001,0.224,0.000,0.0
324,EGY,Egypt,2001,3.770000e+11,70153000.0,555.354,8.895,0.000,235.813,242.550,310.647,436.579,40.274,40.274,0.0,39.778,0.002,0.494,0.000,0.0
325,EGY,Egypt,2002,3.880000e+11,71485000.0,565.768,9.542,0.000,255.063,262.763,301.163,432.405,38.957,38.957,0.0,38.372,0.003,0.583,0.000,0.0
326,EGY,Egypt,2003,4.010000e+11,72826000.0,605.183,9.894,0.000,285.863,289.713,309.426,430.453,36.032,36.032,0.0,35.251,0.003,0.779,0.000,0.0
327,EGY,Egypt,2004,4.200000e+11,74172000.0,635.097,10.113,0.000,305.113,317.625,319.872,404.539,36.102,36.102,0.0,34.735,0.003,1.364,0.000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1338,VNM,Vietnam,2012,4.500000e+11,89802000.0,483.873,187.222,272.851,90.276,90.276,206.375,197.322,137.569,137.569,0.0,137.302,0.015,0.105,0.147,0.0
1339,VNM,Vietnam,2013,4.750000e+11,90753000.0,514.644,199.971,266.244,94.097,94.097,220.576,196.365,148.372,148.372,0.0,148.032,0.015,0.176,0.148,0.0
1340,VNM,Vietnam,2014,5.070000e+11,91714000.0,567.055,241.617,266.387,98.527,98.527,226.911,184.071,158.547,158.547,0.0,158.204,0.017,0.175,0.150,0.0
1341,VNM,Vietnam,2015,5.410000e+11,92677000.0,659.056,305.124,270.134,102.869,102.869,251.063,199.351,145.270,145.270,0.0,144.629,0.017,0.447,0.177,0.0
1342,VNM,Vietnam,2016,5.750000e+11,93640000.0,697.203,330.180,251.144,102.387,102.387,264.637,180.100,166.811,166.811,0.0,166.096,0.017,0.528,0.171,0.0